# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Heroku login credentials
      run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    - name: Add Heroku remote
      id: add
      run: | 
        heroku git:remote --app $HEROKU_API_NAME
        echo ::set-output name=exit_code::$?
      env:
          HEROKU_API_NAME: ${{ secrets.HEROKU_API_NAME }}
          
    - name: Push to Heroku
      if: steps.add.outputs.exit_code == 0
      run: git push heroku main
